version: '3'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./backend/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  app:
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - "8000:8000"

volumes:
  db-data:
