version: '3'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./backend/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  app:
    container_name: invest-api
    build: ./backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  celery-worker:
    container_name: invest-celery-worker
    build: ./backend
    env_file:
      - ./backend/.env
    command: celery -A src.worker worker -l info -E -B
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
    restart: unless-stopped

  frontend:
    container_name: invest-frontend
    build: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  db-data:
    driver: "local"
