version: '3'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  app:
    container_name: invest-api
    build: ./backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c ./cmd/start.sh
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  celery-worker:
    container_name: invest-celery-worker
    build: ./backend
    env_file:
      - ./backend/.env
    command: celery -A src.worker worker -l info -E -B
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - backtest-results:/src/backtest-results
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    container_name: invest-frontend
    build: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - app
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  backtest-results:
    external: true
