version: '3'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  app:
    container_name: invest-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"

  redis:
    image: redis:7-alpine

  celery-worker:
    build: .
    env_file:
      - .env
    command: celery -A src.worker worker -l info -E
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    env_file:
      - .env
    command: celery -A src.worker beat -s /src/celerybeat-schedule
    depends_on:
      - db
      - redis

volumes:
  db-data:
    driver: "local"

  backtest-results:
    driver: "local"
