version: '3'

services:
  app:
    container_name: invest-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - backtest-results:/src/backtest-results
      - ./:/src
    depends_on:
      - redis
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"

  redis:
    image: redis:7-alpine

  celery-worker:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - backtest-results:/src/backtest-results
    env_file:
      - .env
    command: celery -A src.worker worker -l info -E -B
    depends_on:
      - redis

volumes:
  backtest-results:
    driver: "local"
    name: backtest-results
