/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export interface AccountUpdate {
  description?: string;
  is_sandbox?: boolean;
  name?: string;
  token: string;
}
