/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { SubaccountScheme } from "./subaccountScheme";

export interface AccountScheme {
  description?: string;
  id: number;
  is_sandbox?: boolean;
  name?: string;
  subaccounts: SubaccountScheme[];
  user_id: string;
}
