/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export interface ArbitrageResult {
  initial_amount: number;
  final_amount: number;
  revenue: number;
  revenue_relative: number;
  payment_method_from: string;
  payment_method_to: string;
  symbols: string[];
}
