/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export type BacktestReadIntervalRaw =
  (typeof BacktestReadIntervalRaw)[keyof typeof BacktestReadIntervalRaw];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BacktestReadIntervalRaw = {
  "1min": "1min",
  "5min": "5min",
  "15min": "15min",
  hour: "hour",
  day: "day",
} as const;
