/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { BacktestCreateIntervalRaw } from './backtestCreateIntervalRaw';
import type { BacktestCreateRobotConfig } from './backtestCreateRobotConfig';

export interface BacktestCreate {
  broker_fee?: number;
  date_from: string;
  date_to: string;
  figi: string;
  id?: string;
  initial_capital?: number;
  interval_raw: BacktestCreateIntervalRaw;
  robot_config: BacktestCreateRobotConfig;
  robot_id: number;
}
