/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { BacktestReadIntervalRaw } from './backtestReadIntervalRaw';
import type { BacktestReadRobotConfig } from './backtestReadRobotConfig';
import type { BacktestReadResults } from './backtestReadResults';
import type { InstrumentScheme } from './instrumentScheme';

export interface BacktestRead {
  id?: string;
  robot_id: number;
  figi: string;
  date_from: string;
  date_to: string;
  interval_raw: BacktestReadIntervalRaw;
  broker_fee?: number;
  initial_capital?: number;
  robot_config: BacktestReadRobotConfig;
  created_at: string;
  updated_at: string;
  time_elapsed?: number;
  is_started: boolean;
  is_finished: boolean;
  results: BacktestReadResults;
  relative_yield?: number;
  absolute_yield?: number;
  instrument?: InstrumentScheme;
}
