/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export type BacktestCreateIntervalRaw = typeof BacktestCreateIntervalRaw[keyof typeof BacktestCreateIntervalRaw];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BacktestCreateIntervalRaw = {
  '1min': '1min',
  '5min': '5min',
  '15min': '15min',
  hour: 'hour',
  day: 'day',
} as const;
