/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export interface InstrumentScheme {
  uid: string;
  type: string;
  figi: string;
  ticker: string;
  currency: string;
  name: string;
  lot: number;
  image_link?: string;
}
