/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export type ListInstrumentsApiV1InstrumentsGetParams = { type?: string; q?: string; order_by?: string; page?: number; page_size?: number };
