/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { ListPortfolioCostApiV1SubaccountsSubaccountIdPortfolioCostGetRange } from "./listPortfolioCostApiV1SubaccountsSubaccountIdPortfolioCostGetRange";

export type ListPortfolioCostApiV1SubaccountsSubaccountIdPortfolioCostGetParams =
  {
    currency?: string;
    range?: ListPortfolioCostApiV1SubaccountsSubaccountIdPortfolioCostGetRange;
  };
