/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export type ListArbitrageDeltasApiV1ArbitrageDeltasGetParams = {
  order_by?: string;
  is_active?: boolean;
  page?: number;
  page_size?: number;
};
