/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export type ListInstrumentMetricsApiV1InstrumentsMetricsGetParams = { order_by?: string; instrument__type?: string; instrument__q?: string; instrument__order_by?: string; page?: number; page_size?: number };
