/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export type ListArbitrageDeltasApiV1DeltasGetParams = {
order_by?: string;
page?: number;
page_size?: number;
};
