/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export type ListInstrumentsApiV1InstrumentsGetParams = {
type?: string;
q?: string;
order_by?: string;
ticker?: string;
page?: number;
page_size?: number;
};
