/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { OperationTradeScheme } from './operationTradeScheme';

export interface OperationScheme {
  broker_id: string;
  currency: string;
  payment: number;
  price: number;
  type: string;
  state: string;
  quantity: number;
  instrument_figi?: string;
  commission?: number;
  date: string;
  trades: OperationTradeScheme[];
}
