/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export interface OperationTradeScheme {
  date: string;
  quantity: number;
  price: number;
}
