/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { InstrumentScheme } from './instrumentScheme';
import type { OperationTradeScheme } from './operationTradeScheme';

export interface OperationScheme {
  broker_id: string;
  commission?: number;
  currency: string;
  date: string;
  instrument?: InstrumentScheme;
  payment: number;
  price: number;
  quantity: number;
  state: string;
  trades: OperationTradeScheme[];
  type: string;
}
