/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { OrderCreateType } from "./orderCreateType";

export interface OrderCreate {
  figi: string;
  is_limit: boolean;
  price?: string;
  quantity: number;
  type: OrderCreateType;
}
