/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export type OrderCreateType = typeof OrderCreateType[keyof typeof OrderCreateType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderCreateType = {
  buy: 'buy',
  sell: 'sell',
} as const;
