/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { OrderCreateType } from './orderCreateType';

export interface OrderCreate {
  figi: string;
  quantity: number;
  price?: string;
  is_limit: boolean;
  type: OrderCreateType;
}
