/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { InstrumentMetricsScheme } from './instrumentMetricsScheme';

export interface PageInstrumentMetricsScheme {
  count: number;
  items: InstrumentMetricsScheme[];
  page: number;
}
