/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { OperationScheme } from "./operationScheme";

export interface PageOperationScheme {
  count: number;
  items: OperationScheme[];
  page: number;
}
