/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { ArbitrageDeltasScheme } from './arbitrageDeltasScheme';

export interface PageArbitrageDeltasScheme {
  count: number;
  items: ArbitrageDeltasScheme[];
  page: number;
}
