/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { InstrumentScheme } from './instrumentScheme';

export interface PageInstrumentScheme {
  count: number;
  items: InstrumentScheme[];
  page: number;
}
