/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { PortfolioCostScheme } from './portfolioCostScheme';
import type { PortfolioPositionScheme } from './portfolioPositionScheme';

export interface PortfolioScheme {
  cost?: PortfolioCostScheme[];
  date_added: string;
  positions?: PortfolioPositionScheme[];
}
