/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { InstrumentScheme } from "./instrumentScheme";

export interface PortfolioPositionScheme {
  average_price: number;
  blocked: number;
  current_nkd: number;
  current_price: number;
  expected_yield: number;
  instrument: InstrumentScheme;
  quantity: number;
  var_margin: number;
}
