/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export interface RobotScheme {
  avg_yield?: number;
  config?: unknown;
  creator: string;
  description?: string;
  id: number;
  image: string;
  name: string;
  used_by?: number;
}
