/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export interface SubaccountScheme {
  broker_id: string;
  description?: string;
  id: number;
  is_enabled?: boolean;
  name?: string;
  type: string;
}
