/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Base User model.
 */
export interface UserRead {
  email: string;
  id?: unknown;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
}
