/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export interface WorkerCreate {
  config?: unknown;
  is_enabled: boolean;
  robot_id: number;
  subaccount_id: number;
}
