/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */

export interface WorkersStats {
  active?: number;
  created?: number;
  dead?: number;
  exited?: number;
  paused?: number;
  restarting?: number;
  running?: number;
}
