/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkerCreateConfig } from './workerCreateConfig';

export interface WorkerCreate {
  subaccount_id: number;
  config: WorkerCreateConfig;
  is_enabled: boolean;
  robot_id: number;
}
