/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import type { RobotScheme } from './robotScheme';

export interface WorkerScheme {
  config?: unknown;
  container_name: string;
  id: number;
  robot: RobotScheme;
  status?: string;
  subaccount_id: number;
}
