"""Add metrics.

Revision ID: 85727ffc6696
Revises: ae71d21ea81d
Create Date: 2023-06-23 11:32:19.737129

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "85727ffc6696"
down_revision = "ae71d21ea81d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instrument_metrics",
        sa.Column("figi", sa.String(), nullable=True),
        sa.Column("volatility", sa.Float(), nullable=True),
        sa.Column("buy_volume", sa.Float(), nullable=True),
        sa.Column("sell_volume", sa.Float(), nullable=True),
        sa.Column("spread", sa.Float(), nullable=True),
        sa.Column("last_price", sa.Float(), nullable=True),
        sa.Column("relative_price", sa.Float(), nullable=True),
        sa.Column("gain", sa.Float(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("instrument_metrics_pkey")),
    )
    op.create_index(
        op.f("instrument_metrics_id_idx"), "instrument_metrics", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("instrument_metrics_id_idx"), table_name="instrument_metrics")
    op.drop_table("instrument_metrics")
    # ### end Alembic commands ###
