"""Add operation models.

Revision ID: b4a0095fab57
Revises: 4bc018fd4ed8
Create Date: 2023-05-02 08:49:31.740677

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b4a0095fab57"
down_revision = "4bc018fd4ed8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operations",
        sa.Column("subaccount_id", sa.BigInteger(), nullable=True),
        sa.Column("broker_id", sa.String(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("payment", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("price", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("quantity", sa.BigInteger(), nullable=True),
        sa.Column("instrument_uid", sa.UUID(), nullable=True),
        sa.Column("commission", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_uid"],
            ["instruments.uid"],
            name=op.f("operations_instrument_uid_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["subaccount_id"],
            ["subaccounts.id"],
            name=op.f("operations_subaccount_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("operations_pkey")),
    )
    op.create_index(op.f("operations_id_idx"), "operations", ["id"], unique=False)
    op.create_table(
        "operation_trades",
        sa.Column("operation_id", sa.BigInteger(), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("quantity", sa.BigInteger(), nullable=True),
        sa.Column("price", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("operation_trades_operation_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("operation_trades_pkey")),
    )
    op.create_index(
        op.f("operation_trades_id_idx"), "operation_trades", ["id"], unique=False
    )
    op.add_column(
        "subaccounts",
        sa.Column("opened_date", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subaccounts", "opened_date")
    op.drop_index(op.f("operation_trades_id_idx"), table_name="operation_trades")
    op.drop_table("operation_trades")
    op.drop_index(op.f("operations_id_idx"), table_name="operations")
    op.drop_table("operations")
    # ### end Alembic commands ###
