"""Change models fields

Revision ID: 2e9ecdcd4e16
Revises: 70335e654ce0
Create Date: 2023-04-24 17:40:15.888104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9ecdcd4e16'
down_revision = '70335e654ce0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('subaccount_id', sa.BigInteger(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['subaccount_id'], ['subaccounts.id'], name=op.f('portfolio_subaccount_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolio_pkey'))
    )
    op.create_index(op.f('portfolio_id_idx'), 'portfolio', ['id'], unique=False)
    op.create_table('portfolio_cost',
    sa.Column('portfolio_id', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('value', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['currency'], ['currencies.iso'], name=op.f('portfolio_cost_currency_fkey')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], name=op.f('portfolio_cost_portfolio_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolio_cost_pkey'))
    )
    op.create_index(op.f('portfolio_cost_id_idx'), 'portfolio_cost', ['id'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('portfolio_id', sa.BigInteger(), nullable=True),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('blocked', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('expected_yield', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('var_margin', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('current_nkd', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('portfolio_positions_instrument_id_fkey')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], name=op.f('portfolio_positions_portfolio_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolio_positions_pkey'))
    )
    op.create_index(op.f('portfolio_positions_id_idx'), 'portfolio_positions', ['id'], unique=False)
    op.alter_column('accounts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(op.f('accounts_token_key'), 'accounts', ['token'])
    op.alter_column('subaccounts', 'account_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('subaccounts', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint(op.f('subaccounts_broker_id_key'), 'subaccounts', ['broker_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subaccounts_broker_id_key'), 'subaccounts', type_='unique')
    op.alter_column('subaccounts', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('subaccounts', 'account_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('accounts_token_key'), 'accounts', type_='unique')
    op.alter_column('accounts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('portfolio_positions_id_idx'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('portfolio_cost_id_idx'), table_name='portfolio_cost')
    op.drop_table('portfolio_cost')
    op.drop_index(op.f('portfolio_id_idx'), table_name='portfolio')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
