"""Add models

Revision ID: 70335e654ce0
Revises: 
Create Date: 2023-04-24 09:08:24.624851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = "70335e654ce0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("iso", sa.String(length=3), nullable=False),
        sa.Column("figi", sa.String(length=12), nullable=True),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("lot", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("iso", name=op.f("currencies_pkey")),
    )
    op.create_index(op.f("currencies_iso_idx"), "currencies", ["iso"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", UUID, nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("users_email_idx"), "users", ["email"], unique=True)
    op.create_table(
        "accounts",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("accounts_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("accounts_pkey")),
    )
    op.create_index(op.f("accounts_id_idx"), "accounts", ["id"], unique=False)
    op.create_table(
        "instruments",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("figi", sa.String(length=12), nullable=True),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("lot", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "min_price_increment", sa.Numeric(precision=18, scale=9), nullable=True
        ),
        sa.Column("image_link", sa.String(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency"], ["currencies.iso"], name=op.f("instruments_currency_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("instruments_pkey")),
    )
    op.create_index(op.f("instruments_id_idx"), "instruments", ["id"], unique=False)
    op.create_table(
        "bonds",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("coupon_quantity_per_year", sa.Integer(), nullable=True),
        sa.Column("maturity_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nominal", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("initial_nominal", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("issue_size", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["instruments.id"], name=op.f("bonds_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("bonds_pkey")),
    )
    op.create_table(
        "candles",
        sa.Column("instrument_id", sa.BigInteger(), nullable=True),
        sa.Column("high", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("low", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("open", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("close", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.String(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("candles_instrument_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("candles_pkey")),
    )
    op.create_index(op.f("candles_id_idx"), "candles", ["id"], unique=False)
    op.create_table(
        "etfs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("fixed_commission", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["instruments.id"], name=op.f("etfs_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("etfs_pkey")),
    )
    op.create_table(
        "futures",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("futures_type", sa.String(), nullable=True),
        sa.Column("asset_type", sa.String(), nullable=True),
        sa.Column("basic_asset", sa.BigInteger(), nullable=True),
        sa.Column("basic_asset_size", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["basic_asset"], ["instruments.id"], name=op.f("futures_basic_asset_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["instruments.id"], name=op.f("futures_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("futures_pkey")),
    )
    op.create_table(
        "options",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("direction", sa.String(), nullable=True),
        sa.Column("payment_type", sa.String(), nullable=True),
        sa.Column("style", sa.String(), nullable=True),
        sa.Column("settlement_style", sa.String(), nullable=True),
        sa.Column("basic_asset", sa.BigInteger(), nullable=True),
        sa.Column("basic_asset_size", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("strike_price", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.ForeignKeyConstraint(
            ["basic_asset"], ["instruments.id"], name=op.f("options_basic_asset_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["instruments.id"], name=op.f("options_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("options_pkey")),
    )
    op.create_table(
        "shares",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["instruments.id"], name=op.f("shares_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("shares_pkey")),
    )
    op.create_table(
        "subaccounts",
        sa.Column("account_id", sa.BigInteger(), nullable=True),
        sa.Column("broker_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_enabled", sa.Boolean(), server_default=sa.text("FALSE"), nullable=True
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("subaccounts_account_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("subaccounts_pkey")),
    )
    op.create_index(op.f("subaccounts_id_idx"), "subaccounts", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("subaccounts_id_idx"), table_name="subaccounts")
    op.drop_table("subaccounts")
    op.drop_table("shares")
    op.drop_table("options")
    op.drop_table("futures")
    op.drop_table("etfs")
    op.drop_index(op.f("candles_id_idx"), table_name="candles")
    op.drop_table("candles")
    op.drop_table("bonds")
    op.drop_index(op.f("instruments_id_idx"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_index(op.f("accounts_id_idx"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("users_email_idx"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("currencies_iso_idx"), table_name="currencies")
    op.drop_table("currencies")
    # ### end Alembic commands ###
