"""Change operation fk from uid to figi

Revision ID: d8b97ceab6ae
Revises: b4a0095fab57
Create Date: 2023-05-02 09:30:28.617717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b97ceab6ae'
down_revision = 'b4a0095fab57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('instrument_figi', sa.String(length=12), nullable=True))
    op.alter_column('operations', 'broker_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('operations_instrument_uid_fkey', 'operations', type_='foreignkey')
    op.drop_column('operations', 'instrument_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('instrument_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('operations_instrument_uid_fkey', 'operations', 'instruments', ['instrument_uid'], ['uid'])
    op.alter_column('operations', 'broker_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('operations', 'instrument_figi')
    # ### end Alembic commands ###
