"""Add metrics

Revision ID: 85727ffc6696
Revises: ae71d21ea81d
Create Date: 2023-06-23 11:32:19.737129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85727ffc6696'
down_revision = 'ae71d21ea81d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_metrics',
    sa.Column('figi', sa.String(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('buy_volume', sa.Float(), nullable=True),
    sa.Column('sell_volume', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('relative_price', sa.Float(), nullable=True),
    sa.Column('gain', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('instrument_metrics_pkey'))
    )
    op.create_index(op.f('instrument_metrics_id_idx'), 'instrument_metrics', ['id'], unique=False)
    op.drop_index('candles_id_idx', table_name='candles')
    op.drop_table('candles')
    op.drop_index('instruments_figi_idx', table_name='instruments')
    op.drop_index('operations_subaccount_id_idx', table_name='operations')
    op.drop_index('portfolio_cost_portfolio_id_idx', table_name='portfolio_cost')
    op.drop_index('portfolio_positions_portfolio_id_idx', table_name='portfolio_positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('portfolio_positions_portfolio_id_idx', 'portfolio_positions', ['portfolio_id'], unique=False)
    op.create_index('portfolio_cost_portfolio_id_idx', 'portfolio_cost', ['portfolio_id'], unique=False)
    op.create_index('operations_subaccount_id_idx', 'operations', ['subaccount_id'], unique=False)
    op.create_index('instruments_figi_idx', 'instruments', ['figi'], unique=False)
    op.create_table('candles',
    sa.Column('instrument_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('high', sa.NUMERIC(precision=18, scale=9), autoincrement=False, nullable=True),
    sa.Column('low', sa.NUMERIC(precision=18, scale=9), autoincrement=False, nullable=True),
    sa.Column('open', sa.NUMERIC(precision=18, scale=9), autoincrement=False, nullable=True),
    sa.Column('close', sa.NUMERIC(precision=18, scale=9), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['instrument_uid'], ['instruments.uid'], name='candles_instrument_uid_fkey'),
    sa.PrimaryKeyConstraint('id', name='candles_pkey')
    )
    op.create_index('candles_id_idx', 'candles', ['id'], unique=False)
    op.drop_index(op.f('instrument_metrics_id_idx'), table_name='instrument_metrics')
    op.drop_table('instrument_metrics')
    # ### end Alembic commands ###
