"""Add robot models.

Revision ID: a34c7666e786
Revises: d8b97ceab6ae
Create Date: 2023-05-11 12:09:44.284957

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a34c7666e786"
down_revision = "d8b97ceab6ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "robots",
        sa.Column("creator_id", sa.UUID(), nullable=True),
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], name=op.f("robots_creator_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("robots_pkey")),
    )
    op.create_index(op.f("robots_id_idx"), "robots", ["id"], unique=False)
    op.create_table(
        "workers",
        sa.Column("robot_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("subaccount_id", sa.BigInteger(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=True),
        sa.Column("container_name", sa.String(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"], ["robots.id"], name=op.f("workers_robot_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["subaccount_id"],
            ["subaccounts.id"],
            name=op.f("workers_subaccount_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("workers_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("workers_pkey")),
    )
    op.create_index(op.f("workers_id_idx"), "workers", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("workers_id_idx"), table_name="workers")
    op.drop_table("workers")
    op.drop_index(op.f("robots_id_idx"), table_name="robots")
    op.drop_table("robots")
    # ### end Alembic commands ###
