"""Create models

Revision ID: e21db593fdad
Revises: 
Create Date: 2023-04-27 08:28:24.368870

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e21db593fdad"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("iso", sa.String(length=3), nullable=False),
        sa.Column("figi", sa.String(length=12), nullable=True),
        sa.Column("uid", sa.UUID(), nullable=True),
        sa.Column("position_uid", sa.UUID(), nullable=True),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("lot", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("image_link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("iso", name=op.f("currencies_pkey")),
    )
    op.create_index(op.f("currencies_iso_idx"), "currencies", ["iso"], unique=False)
    op.create_index(
        op.f("currencies_position_uid_idx"), "currencies", ["position_uid"], unique=True
    )
    op.create_index(op.f("currencies_uid_idx"), "currencies", ["uid"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("users_email_idx"), "users", ["email"], unique=True)
    op.create_table(
        "accounts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("accounts_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("accounts_pkey")),
        sa.UniqueConstraint("token", name=op.f("accounts_token_key")),
    )
    op.create_index(op.f("accounts_id_idx"), "accounts", ["id"], unique=False)
    op.create_table(
        "instruments",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("figi", sa.String(length=12), nullable=True),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("lot", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "min_price_increment", sa.Numeric(precision=28, scale=9), nullable=True
        ),
        sa.Column("image_link", sa.String(), nullable=True),
        sa.Column("position_uid", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["currency"], ["currencies.iso"], name=op.f("instruments_currency_fkey")
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("instruments_pkey")),
    )
    op.create_index(
        op.f("instruments_position_uid_idx"),
        "instruments",
        ["position_uid"],
        unique=False,
    )
    op.create_index(op.f("instruments_uid_idx"), "instruments", ["uid"], unique=False)
    op.create_table(
        "bonds",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("coupon_quantity_per_year", sa.Integer(), nullable=True),
        sa.Column("maturity_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nominal", sa.Numeric(precision=28, scale=9), nullable=True),
        sa.Column("initial_nominal", sa.Numeric(precision=28, scale=9), nullable=True),
        sa.Column("issue_size", sa.Numeric(precision=28, scale=9), nullable=True),
        sa.ForeignKeyConstraint(
            ["uid"], ["instruments.uid"], name=op.f("bonds_uid_fkey")
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("bonds_pkey")),
    )
    op.create_table(
        "candles",
        sa.Column("instrument_uid", sa.UUID(), nullable=True),
        sa.Column("high", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("low", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("open", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("close", sa.Numeric(precision=18, scale=9), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.String(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_uid"],
            ["instruments.uid"],
            name=op.f("candles_instrument_uid_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("candles_pkey")),
    )
    op.create_index(op.f("candles_id_idx"), "candles", ["id"], unique=False)
    op.create_table(
        "etfs",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("fixed_commission", sa.Numeric(precision=28, scale=9), nullable=True),
        sa.ForeignKeyConstraint(
            ["uid"], ["instruments.uid"], name=op.f("etfs_uid_fkey")
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("etfs_pkey")),
    )
    op.create_table(
        "futures",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("futures_type", sa.String(), nullable=True),
        sa.Column("asset_type", sa.String(), nullable=True),
        sa.Column("basic_asset", sa.UUID(), nullable=True),
        sa.Column("basic_asset_size", sa.Numeric(precision=28, scale=9), nullable=True),
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["uid"], ["instruments.uid"], name=op.f("futures_uid_fkey")
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("futures_pkey")),
    )
    op.create_table(
        "options",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("direction", sa.String(), nullable=True),
        sa.Column("payment_type", sa.String(), nullable=True),
        sa.Column("style", sa.String(), nullable=True),
        sa.Column("settlement_style", sa.String(), nullable=True),
        sa.Column("settlement_currency", sa.String(length=3), nullable=True),
        sa.Column("asset_type", sa.String(), nullable=True),
        sa.Column("basic_asset", sa.UUID(), nullable=True),
        sa.Column("basic_asset_size", sa.Numeric(precision=28, scale=9), nullable=True),
        sa.Column("strike_price", sa.Numeric(precision=28, scale=9), nullable=True),
        sa.ForeignKeyConstraint(
            ["settlement_currency"],
            ["currencies.iso"],
            name=op.f("options_settlement_currency_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["uid"], ["instruments.uid"], name=op.f("options_uid_fkey")
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("options_pkey")),
    )
    op.create_table(
        "shares",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uid"], ["instruments.uid"], name=op.f("shares_uid_fkey")
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("shares_pkey")),
    )
    op.create_table(
        "subaccounts",
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("broker_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("subaccounts_account_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("subaccounts_pkey")),
        sa.UniqueConstraint("broker_id", name=op.f("subaccounts_broker_id_key")),
    )
    op.create_index(op.f("subaccounts_id_idx"), "subaccounts", ["id"], unique=False)
    op.create_table(
        "portfolio",
        sa.Column("subaccount_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "date_added",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subaccount_id"],
            ["subaccounts.id"],
            name=op.f("portfolio_subaccount_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("portfolio_pkey")),
    )
    op.create_index(op.f("portfolio_id_idx"), "portfolio", ["id"], unique=False)
    op.create_table(
        "portfolio_cost",
        sa.Column("portfolio_id", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("value", sa.Numeric(precision=11, scale=2), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency"], ["currencies.iso"], name=op.f("portfolio_cost_currency_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolio.id"],
            name=op.f("portfolio_cost_portfolio_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("portfolio_cost_pkey")),
    )
    op.create_index(
        op.f("portfolio_cost_id_idx"), "portfolio_cost", ["id"], unique=False
    )
    op.create_table(
        "portfolio_positions",
        sa.Column("portfolio_id", sa.BigInteger(), nullable=True),
        sa.Column("instrument_uid", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=11, scale=2), nullable=True),
        sa.Column("blocked", sa.Numeric(precision=11, scale=2), nullable=True),
        sa.Column("average_price", sa.Numeric(precision=11, scale=2), nullable=True),
        sa.Column("expected_yield", sa.Numeric(precision=11, scale=2), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=11, scale=2), nullable=True),
        sa.Column("var_margin", sa.Numeric(precision=11, scale=2), nullable=True),
        sa.Column("current_nkd", sa.Numeric(precision=11, scale=2), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_uid"],
            ["instruments.uid"],
            name=op.f("portfolio_positions_instrument_uid_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolio.id"],
            name=op.f("portfolio_positions_portfolio_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("portfolio_positions_pkey")),
    )
    op.create_index(
        op.f("portfolio_positions_id_idx"), "portfolio_positions", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("portfolio_positions_id_idx"), table_name="portfolio_positions")
    op.drop_table("portfolio_positions")
    op.drop_index(op.f("portfolio_cost_id_idx"), table_name="portfolio_cost")
    op.drop_table("portfolio_cost")
    op.drop_index(op.f("portfolio_id_idx"), table_name="portfolio")
    op.drop_table("portfolio")
    op.drop_index(op.f("subaccounts_id_idx"), table_name="subaccounts")
    op.drop_table("subaccounts")
    op.drop_table("shares")
    op.drop_table("options")
    op.drop_table("futures")
    op.drop_table("etfs")
    op.drop_index(op.f("candles_id_idx"), table_name="candles")
    op.drop_table("candles")
    op.drop_table("bonds")
    op.drop_index(op.f("instruments_uid_idx"), table_name="instruments")
    op.drop_index(op.f("instruments_position_uid_idx"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_index(op.f("accounts_id_idx"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("users_email_idx"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("currencies_uid_idx"), table_name="currencies")
    op.drop_index(op.f("currencies_position_uid_idx"), table_name="currencies")
    op.drop_index(op.f("currencies_iso_idx"), table_name="currencies")
    op.drop_table("currencies")
    # ### end Alembic commands ###
