"""Change deltas model

Revision ID: e3f06c735a77
Revises: 9e0c7c13ef1d
Create Date: 2023-11-30 14:44:16.475830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f06c735a77'
down_revision = '9e0c7c13ef1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitrage_deltas', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('arbitrage_deltas', sa.Column('multiplier', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arbitrage_deltas', 'multiplier')
    op.drop_column('arbitrage_deltas', 'is_active')
    # ### end Alembic commands ###
