"""Change some fields of bakctest

Revision ID: fedd30ae8e12
Revises: 589dafc056a9
Create Date: 2023-05-27 09:21:31.679245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fedd30ae8e12'
down_revision = '589dafc056a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_results', sa.Column('time_elapsed', sa.Float(), nullable=True))
    op.drop_column('backtest_results', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_results', sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('backtest_results', 'time_elapsed')
    # ### end Alembic commands ###
