"""Add models

Revision ID: 9b9d3df2baf4
Revises: 823649d47178
Create Date: 2023-04-21 12:37:33.871719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b9d3df2baf4'
down_revision = '823649d47178'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('iso', sa.String(length=3), nullable=False),
    sa.Column('figi', sa.String(length=12), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('lot', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('iso')
    )
    op.create_index(op.f('ix_currencies_iso'), 'currencies', ['iso'], unique=False)
    op.create_table('accounts',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('instruments',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('figi', sa.String(length=12), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('lot', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('min_price_increment', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['currency'], ['currencies.iso'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_id'), 'instruments', ['id'], unique=False)
    op.create_table('bonds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('coupon_quantity_per_year', sa.Integer(), nullable=True),
    sa.Column('maturity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nominal', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('initial_nominal', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('issue_size', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candles',
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('open', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candles_id'), 'candles', ['id'], unique=False)
    op.create_table('etfs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fixed_commission', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('futures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('futures_type', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('basic_asset', sa.BigInteger(), nullable=True),
    sa.Column('basic_asset_size', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['basic_asset'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('settlement_style', sa.String(), nullable=True),
    sa.Column('basic_asset', sa.BigInteger(), nullable=True),
    sa.Column('basic_asset_size', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('strike_price', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.ForeignKeyConstraint(['basic_asset'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shares',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subaccounts',
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('broker_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subaccounts_id'), 'subaccounts', ['id'], unique=False)
    op.create_table('portfolio',
    sa.Column('subaccount_id', sa.BigInteger(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['subaccount_id'], ['subaccounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_id'), 'portfolio', ['id'], unique=False)
    op.create_table('portfolio_cost',
    sa.Column('portfolio_id', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('value', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['currency'], ['currencies.iso'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_cost_id'), 'portfolio_cost', ['id'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('portfolio_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('blocked', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('expected_yield', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('var_margin', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('current_nkd', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_positions_id'), 'portfolio_positions', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_portfolio_positions_id'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('ix_portfolio_cost_id'), table_name='portfolio_cost')
    op.drop_table('portfolio_cost')
    op.drop_index(op.f('ix_portfolio_id'), table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_subaccounts_id'), table_name='subaccounts')
    op.drop_table('subaccounts')
    op.drop_table('shares')
    op.drop_table('options')
    op.drop_table('futures')
    op.drop_table('etfs')
    op.drop_index(op.f('ix_candles_id'), table_name='candles')
    op.drop_table('candles')
    op.drop_table('bonds')
    op.drop_index(op.f('ix_instruments_id'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_currencies_iso'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
