/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Invest API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery,
  useMutation
} from 'react-query'
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from 'react-query'
import type {
  PageRobotScheme,
  HTTPValidationError,
  ListRobotsApiV1RobotsGetParams,
  RobotBacktestScheme,
  PageWorkerScheme,
  ListWorkersApiV1WorkersGetParams,
  WorkerScheme,
  WorkerCreate,
  WorkersStats,
  ContainerStatus,
  GetWorkerStatusApiV1WorkersWorkerIdStatusGetParams
} from '../../models'
import { customInstance } from '.././axios'
import type { ErrorType } from '.././axios'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


// eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary List Robots
 */
export const listRobotsApiV1RobotsGet = (
    params?: ListRobotsApiV1RobotsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<PageRobotScheme>(
      {url: `/api/v1/robots`, method: 'get',
        params, signal
    },
      options);
    }
  

export const getListRobotsApiV1RobotsGetQueryKey = (params?: ListRobotsApiV1RobotsGetParams,) => [`/api/v1/robots`, ...(params ? [params]: [])];

    
export type ListRobotsApiV1RobotsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listRobotsApiV1RobotsGet>>>
export type ListRobotsApiV1RobotsGetQueryError = ErrorType<HTTPValidationError>

export const useListRobotsApiV1RobotsGet = <TData = Awaited<ReturnType<typeof listRobotsApiV1RobotsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListRobotsApiV1RobotsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listRobotsApiV1RobotsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListRobotsApiV1RobotsGetQueryKey(params);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listRobotsApiV1RobotsGet>>> = ({ signal }) => listRobotsApiV1RobotsGet(params, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof listRobotsApiV1RobotsGet>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

/**
 * @summary List Robot Backtests
 */
export const listRobotBacktestsApiV1RobotsRobotIdBacktestsGet = (
    robotId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<RobotBacktestScheme>(
      {url: `/api/v1/robots/${robotId}/backtests`, method: 'get', signal
    },
      options);
    }
  

export const getListRobotBacktestsApiV1RobotsRobotIdBacktestsGetQueryKey = (robotId: number,) => [`/api/v1/robots/${robotId}/backtests`];

    
export type ListRobotBacktestsApiV1RobotsRobotIdBacktestsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listRobotBacktestsApiV1RobotsRobotIdBacktestsGet>>>
export type ListRobotBacktestsApiV1RobotsRobotIdBacktestsGetQueryError = ErrorType<HTTPValidationError>

export const useListRobotBacktestsApiV1RobotsRobotIdBacktestsGet = <TData = Awaited<ReturnType<typeof listRobotBacktestsApiV1RobotsRobotIdBacktestsGet>>, TError = ErrorType<HTTPValidationError>>(
 robotId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listRobotBacktestsApiV1RobotsRobotIdBacktestsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListRobotBacktestsApiV1RobotsRobotIdBacktestsGetQueryKey(robotId);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listRobotBacktestsApiV1RobotsRobotIdBacktestsGet>>> = ({ signal }) => listRobotBacktestsApiV1RobotsRobotIdBacktestsGet(robotId, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof listRobotBacktestsApiV1RobotsRobotIdBacktestsGet>>, TError, TData>(queryKey, queryFn, {enabled: !!(robotId), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

/**
 * @summary List Workers
 */
export const listWorkersApiV1WorkersGet = (
    params?: ListWorkersApiV1WorkersGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<PageWorkerScheme>(
      {url: `/api/v1/workers`, method: 'get',
        params, signal
    },
      options);
    }
  

export const getListWorkersApiV1WorkersGetQueryKey = (params?: ListWorkersApiV1WorkersGetParams,) => [`/api/v1/workers`, ...(params ? [params]: [])];

    
export type ListWorkersApiV1WorkersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listWorkersApiV1WorkersGet>>>
export type ListWorkersApiV1WorkersGetQueryError = ErrorType<HTTPValidationError>

export const useListWorkersApiV1WorkersGet = <TData = Awaited<ReturnType<typeof listWorkersApiV1WorkersGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListWorkersApiV1WorkersGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWorkersApiV1WorkersGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListWorkersApiV1WorkersGetQueryKey(params);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listWorkersApiV1WorkersGet>>> = ({ signal }) => listWorkersApiV1WorkersGet(params, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof listWorkersApiV1WorkersGet>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

/**
 * @summary Create Worker
 */
export const createWorkerApiV1WorkersPost = (
    workerCreate: WorkerCreate,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<WorkerScheme>(
      {url: `/api/v1/workers`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: workerCreate
    },
      options);
    }
  


    export type CreateWorkerApiV1WorkersPostMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkerApiV1WorkersPost>>>
    export type CreateWorkerApiV1WorkersPostMutationBody = WorkerCreate
    export type CreateWorkerApiV1WorkersPostMutationError = ErrorType<HTTPValidationError>

    export const useCreateWorkerApiV1WorkersPost = <TError = ErrorType<HTTPValidationError>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkerApiV1WorkersPost>>, TError,{data: WorkerCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
      const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWorkerApiV1WorkersPost>>, {data: WorkerCreate}> = (props) => {
          const {data} = props ?? {};

          return  createWorkerApiV1WorkersPost(data,requestOptions)
        }

      return useMutation<Awaited<ReturnType<typeof createWorkerApiV1WorkersPost>>, TError, {data: WorkerCreate}, TContext>(mutationFn, mutationOptions)
    }
    /**
 * @summary Get Active Workers Count
 */
export const getActiveWorkersCountApiV1WorkersStatsActiveGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<WorkersStats>(
      {url: `/api/v1/workers/stats/active`, method: 'get', signal
    },
      options);
    }
  

export const getGetActiveWorkersCountApiV1WorkersStatsActiveGetQueryKey = () => [`/api/v1/workers/stats/active`];

    
export type GetActiveWorkersCountApiV1WorkersStatsActiveGetQueryResult = NonNullable<Awaited<ReturnType<typeof getActiveWorkersCountApiV1WorkersStatsActiveGet>>>
export type GetActiveWorkersCountApiV1WorkersStatsActiveGetQueryError = ErrorType<unknown>

export const useGetActiveWorkersCountApiV1WorkersStatsActiveGet = <TData = Awaited<ReturnType<typeof getActiveWorkersCountApiV1WorkersStatsActiveGet>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getActiveWorkersCountApiV1WorkersStatsActiveGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetActiveWorkersCountApiV1WorkersStatsActiveGetQueryKey();

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getActiveWorkersCountApiV1WorkersStatsActiveGet>>> = ({ signal }) => getActiveWorkersCountApiV1WorkersStatsActiveGet(requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof getActiveWorkersCountApiV1WorkersStatsActiveGet>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

/**
 * @summary Read Worker
 */
export const readWorkerApiV1WorkersWorkerIdGet = (
    workerId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<WorkerScheme>(
      {url: `/api/v1/workers/${workerId}`, method: 'get', signal
    },
      options);
    }
  

export const getReadWorkerApiV1WorkersWorkerIdGetQueryKey = (workerId: number,) => [`/api/v1/workers/${workerId}`];

    
export type ReadWorkerApiV1WorkersWorkerIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof readWorkerApiV1WorkersWorkerIdGet>>>
export type ReadWorkerApiV1WorkersWorkerIdGetQueryError = ErrorType<HTTPValidationError>

export const useReadWorkerApiV1WorkersWorkerIdGet = <TData = Awaited<ReturnType<typeof readWorkerApiV1WorkersWorkerIdGet>>, TError = ErrorType<HTTPValidationError>>(
 workerId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof readWorkerApiV1WorkersWorkerIdGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getReadWorkerApiV1WorkersWorkerIdGetQueryKey(workerId);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof readWorkerApiV1WorkersWorkerIdGet>>> = ({ signal }) => readWorkerApiV1WorkersWorkerIdGet(workerId, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof readWorkerApiV1WorkersWorkerIdGet>>, TError, TData>(queryKey, queryFn, {enabled: !!(workerId), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

/**
 * @summary Get Worker Status
 */
export const getWorkerStatusApiV1WorkersWorkerIdStatusGet = (
    workerId: number,
    params?: GetWorkerStatusApiV1WorkersWorkerIdStatusGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<ContainerStatus>(
      {url: `/api/v1/workers/${workerId}/status`, method: 'get',
        params, signal
    },
      options);
    }
  

export const getGetWorkerStatusApiV1WorkersWorkerIdStatusGetQueryKey = (workerId: number,
    params?: GetWorkerStatusApiV1WorkersWorkerIdStatusGetParams,) => [`/api/v1/workers/${workerId}/status`, ...(params ? [params]: [])];

    
export type GetWorkerStatusApiV1WorkersWorkerIdStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkerStatusApiV1WorkersWorkerIdStatusGet>>>
export type GetWorkerStatusApiV1WorkersWorkerIdStatusGetQueryError = ErrorType<HTTPValidationError>

export const useGetWorkerStatusApiV1WorkersWorkerIdStatusGet = <TData = Awaited<ReturnType<typeof getWorkerStatusApiV1WorkersWorkerIdStatusGet>>, TError = ErrorType<HTTPValidationError>>(
 workerId: number,
    params?: GetWorkerStatusApiV1WorkersWorkerIdStatusGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getWorkerStatusApiV1WorkersWorkerIdStatusGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWorkerStatusApiV1WorkersWorkerIdStatusGetQueryKey(workerId,params);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkerStatusApiV1WorkersWorkerIdStatusGet>>> = ({ signal }) => getWorkerStatusApiV1WorkersWorkerIdStatusGet(workerId,params, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof getWorkerStatusApiV1WorkersWorkerIdStatusGet>>, TError, TData>(queryKey, queryFn, {enabled: !!(workerId), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

